version: '3.8'
services:
  python:
    container_name: is238python
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
  
  redis:
    container_name: is238redis
    restart: unless-stopped
    image: bitnami/redis:latest
    ports:
      - '6380:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes